name: Code Review by ChatGPT

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  models: true # GitHub Models 사용 시 필요

jobs:
  chatgpt-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Run ChatGPT Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_GITHUB_MODELS: true
          MODEL: openai/gpt-4o

          LANGUAGE: Korean
          LOG_LEVEL: debug
          INCLUDE_PATTERNS: src/*,.github/**/*